name: Build, Push and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: your-docker-username/node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          
    - name: Update Kubernetes manifests
      run: |
        # Update image tag in k8s manifests
        sed -i "s|${{ env.DOCKER_IMAGE }}:.*|${{ env.DOCKER_IMAGE }}:${{ github.sha }}|g" k8s/base/deployment.yaml
        
        # Commit changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s/base/deployment.yaml
        git commit -m "Update image to ${{ github.sha }} [skip ci]"
        git push
