name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: prathaban1994/my_app:${{ github.sha }}
        
    - name: Update Kubernetes manifests
      run: |
        # Update image tag in k8s manifests
        sed -i "s|prathaban1994/my_app:.*|prathaban1994/my_app:${{ github.sha }}|g" k8s/base/deployment.yaml
        
        # Commit changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s/base/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}"
        git push
